Improve CI test setup
Signed-off-by: Lukas Heumos <lukas.heumos@posteo.net>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,7 +15,8 @@ jobs:
         runs-on: ${{ matrix.os }}
         defaults:
             run:
-                shell: bash -e {0} # -e to fail on error
+              # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
+              shell: bash -euo pipefail {0}
 
         strategy:
             fail-fast: false
@@ -38,6 +39,9 @@ jobs:
 
         steps:
             - uses: actions/checkout@v4
+              with:
+                filter: blob:none
+                fetch-depth: 0
 
             - name: Cache .pertpy_cache
               uses: actions/cache@v4
@@ -53,14 +57,23 @@ jobs:
                   python-version: ${{ matrix.python }}
             - name: Install R
               uses: r-lib/actions/setup-r@v2
+
+            - name: Cache R packages
+              uses: actions/cache@v3
               with:
-                  r-version: "4.4.3"
+                path: ${{ env.R_LIBS_USER }}
+                key: ${{ runner.os }}-r-${{ hashFiles('**/pertpy/tools/_milo.py') }}
+                restore-keys: ${{ runner.os }}-r-
 
             - name: Install edgeR
+              if: steps.cache.outputs.cache-hit != 'true'
               run: Rscript --vanilla -e "install.packages(c('BiocManager', 'statmod'), repos='https://cran.r-project.org'); library('BiocManager'); BiocManager::install('edgeR')"
 
-            - name: Install test dependencies
-              run: python -m pip install --upgrade uv wheel
+            - name: Install uv
+              uses: astral-sh/setup-uv@v5
+              with:
+                enable-cache: true
+                cache-dependency-glob: pyproject.toml
             - name: Install dependencies
               run: |
                   uv pip install --system rpy2
